### ISSUE TITLE
Power of meta analyses

### ISSUE THREAD

**Issue by soodoku** [ecsalomon/TSR---Test-Stats-Replication#2]
What is the power of your own analyses to discover patterns? How big does a slope have to be to see an effect etc. reliably?

**Comment by not-the-fish** [comment]
Quite low. Some papers are excluded for being single-study papers (i.e., inappropriate to calculate some metrics, such as cor(ES, N) and p-curve). Others are excluded from the effect size difference calculation because there was insufficient information to calculate a Cohen's d in the initial report. 

For the effect size difference analyses, there are 12 included effects. This is 80% power for r = .72 (calculated using pwr package in R), which is likely an unreasonable expectation. If you want to add a Bonferroni correction for 6 different analyses, there is 80% power for r = .82. Correct for 12 analyses, 80% power for r = .84. 

For the logistic regressions, there are 16 effects. The power calculations are more complex, but I would expect them to also be underpowered.

**Comment by soodoku** [comment]
Righto. Thanks for this. I will think more.
